MittInternPortal/Models/Apply.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MittInternPortal.Models
{
    public class Apply
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public int EmployerId { get; set; }
        public virtual Employer Employer { get; set; }



    }
}

MittInternPortal/Controllers/ApplyController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MittInternPortal.Models;

namespace MittInternPortal.Controllers
{
    public class ApplyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Apply
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ApplyJobs()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ApplyJobs(Models.Apply sm, HttpPostedFileBase file /*Resume r*/)
        {
            ViewBag.FullName = sm.FullName;
            ViewBag.Email = sm.Email;
            ViewBag.EmployerId = sm.Employer.CompanyName;

            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedResume"), _FileName);
                    file.SaveAs(_path);
                    //r.Name = _FileName;
                    //db.Resume.Add(r);
                    //db.SaveChanges();

                }
                ViewBag.Message = "File Uploded Successfully!";
                return View("JobApplied");
            }
            catch
            {
                ViewBag.Message = "File Upload failed!";
                return View();
            }

        }


        public ActionResult ApplyJob()
        {
            return View();
        }
        public ActionResult SubmitResume()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SubmitResume(HttpPostedFileBase file /*Resume r*/)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedResume"), _FileName);
                    file.SaveAs(_path);
                    //r.Name = _FileName;
                    //db.Resume.Add(r);
                    //db.SaveChanges();

                }
                ViewBag.Message = "File Uploded Successfully!";
                return View();
            }
            catch
            {
                ViewBag.Message = "File Upload failed!";
                return View();
            }
        }

        public ActionResult JobApplied()
        {
            return View();
        }


    }
}

MittInternPortal/Views/Apply/ApplyJob.cshtml
@model IEnumerable<MittInternPortal.Models.Apply>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            <b>FullName:</b>    @ViewBag.FullName <br />
        </th>
        <th>
            <b>Email:</b>  @ViewBag.Email<br />
        </th>
        <th>
            <b>EmployerId  @ViewBag.EmployerId</b>
        </th>

    </tr>


</table>

MittInternPortal/Views/Apply/ApplyJobs.cshtml
@model MittInternPortal.Models.Apply
<h4 style="color:purple">

    <b>FullName:</b>    @ViewBag.FullName <br />
    <b>Email:</b>  @ViewBag.Email<br />
    <b>EmployerId  @ViewBag.EmployerId</b>

</h4>
<hr />
<h3><b>Apply</b></h3>


@using (Html.BeginForm("ApplyJobs", "Apply", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>Enter FulName: </td>
            <td>@Html.TextBoxFor(m => m.FullName)</td>
        </tr>
        <tr>
            <td>Enter Email: </td>
            <td>@Html.TextBoxFor(m => m.Email)</td>
        </tr>
        <tr>
            <td>Enter Employer: </td>
            <td>   @Html.TextBoxFor(m => m.Employer.CompanyName)</td>
        </tr>
        <tr>
            <td>upload resume:</td>
            <td>

                <div>
                    @Html.TextBox("file", "", new { type = "file" })<br />

                    @ViewBag.Message
                </div>

            </td>
        </tr>

        <tr>
            <td colspan="2"><input type="submit" value="Submit Form" /></td>
        </tr>
    </table>}

MittInternPortal/Views/Apply/JobApplied.cshtml
@{
    ViewBag.Title = "JobApplied";
}

<h2>JobApplied</h2>

<h2> your job application has been submitted </h2>