MittInternPortal/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using MittInternPortal.Models;

namespace MittInternPortal.Controllers
{
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }
        // GET: Role
      



            /// <summary>
            /// Get All Roles
            /// </summary>
            /// <returns></returns>
            public ActionResult Index()
            {
                var Roles = context.Roles.ToList();
                return View(Roles);
            }

            /// <summary>
            /// Create  a New role
            /// </summary>
            /// <returns></returns>
            public ActionResult Create()
            {
                var Role = new IdentityRole();
                return View(Role);
            }

            /// <summary>
            /// Create a New Role
            /// </summary>
            /// <param name="Role"></param>
            /// <returns></returns>
            [HttpPost]
            public ActionResult Create(IdentityRole Role)
            {
                context.Roles.Add(Role);
                context.SaveChanges();
                return RedirectToAction("Index");
            }


        }
    
}

MittInternPortal/Views/Role/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>


@using (Html.BeginForm())
{
    <table id="tbrole">
        <tr>
            <td class="c">Enter Role Name To be Created:</td>
            <td class="c">
                @Html.EditorFor(m => m.Name)
            </td>
        </tr>
    </table>
    <input type="submit" value="Create Role" />
}

MittInternPortal/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Available Roles For Application</h2>

@Html.ActionLink("Create Role", "Create", "Role")

<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>

<table id="tbrole">
    <tr>
        <td class="c">
            Role Name
        </td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
            </td>
        </tr>
    }
</table>